In [1]:
import sys
import pandas as pd
import numpy as np

sys.path.append('.')
data_daily = pd.read_csv('./data/48_Industry_Portfolios_Daily.csv', index_col=0)

# Trim the data
data_daily = data_daily.iloc[('197401' <= data_daily.index.values.astype(str)) & (data_daily.index.values.astype(str) <= '202012')]

# Convert the index to datetime
data_daily.index = pd.to_datetime(data_daily.index, format='%Y%m%d')
daily_date = data_daily.index.date

# The rate of return matrix, fill the missing values with 100%
Return = data_daily.values.T.astype(float)
Return[Return < -99]
Gross_return = (Return + 100) / 100 # Gross Return

print(Gross_return.shape)

# Check the first few rows of the dataset
data_daily.head()

window_size = 120

(48, 11834)


In [2]:
# Check the first few rows of the dataset
data_daily.head()

Agric  Food   Soda   Beer   Smoke  Toys   Fun    Books  Hshld  \
1974-01-02  -0.61   0.20  -0.82  -0.60   0.76   0.26  -1.86   0.95  -0.20   
1974-01-03   3.79   2.64   2.09   2.22   2.97   4.60   0.64   1.40   0.73   
1974-01-04   0.46   0.55  -1.28  -0.65  -0.24  -0.45  -2.58  -0.38  -2.39   
1974-01-07  -1.55   0.01  -1.18  -1.37  -0.81  -1.08   3.15  -0.28  -1.78   
1974-01-08  -1.31  -1.20  -2.41  -2.53  -2.30  -2.79  -4.72  -0.96  -2.20   

            Clths  ...  Boxes  Trans  Whlsl  Rtail  Meals  Banks  Insur  \
1974-01-02   1.43  ...   1.13   1.04   2.43  -0.12   1.12  -0.66   0.23   
1974-01-03   4.42  ...   1.23   2.52   3.70   2.48   0.43   1.33   2.69   
1974-01-04   1.50  ...  -0.61  -0.50   0.86   0.78  -3.86   0.13   0.11   
1974-01-07  -0.09  ...  -1.96  -2.61   0.49  -0.48  -2.17   0.46  -0.15   
1974-01-08  -0.44  ...  -1.57  -3.01  -2.12  -1.96  -2.66  -1.65  -0.17   

            RlEst  Fin    Other  
1974-01-02   2.11   0.80   0.12  
1974-01-03   4.50   2.64   1.72  
1974-01-04   1.41  -0.13  -0.30  
1974-01-07   1.53   0.00   0.14  
1974-01-08  -1.32  -0.78  -1.06  

[5 rows x 48 columns]

In [3]:
print(Gross_return)

# taks the 120 columns from Gross_return starting from the 1200th column
# data = Gross_return[:, 1200:1200 + window_size]
data = Gross_return[:, :window_size]
# Check the shape of the new dataset
print(data.shape)

[[0.9939 1.0379 1.0046 ... 0.9911 0.9955 0.9949]
 [1.002  1.0264 1.0055 ... 0.9961 1.0042 1.0001]
 [0.9918 1.0209 0.9872 ... 0.9951 0.9971 0.991 ]
 ...
 [1.0211 1.045  1.0141 ... 0.9947 1.0005 0.9892]
 [1.008  1.0264 0.9987 ... 1.0009 1.0039 0.9846]
 [1.0012 1.0172 0.997  ... 0.9982 0.9963 0.9853]]
(48, 120)


In [4]:
# convariance matrix
cov_matrix = np.cov(data)
# Check the shape of the covariance matrix
print(cov_matrix.shape)
# Check the first few rows of the covariance matrix
print(cov_matrix[:5, :5])

(48, 48)
[[3.23445812e-04 5.95734174e-05 7.59082983e-05 9.44388305e-05
  9.97317367e-05]
 [5.95734174e-05 6.43317199e-05 7.63622941e-05 6.50720700e-05
  7.23755686e-05]
 [7.59082983e-05 7.63622941e-05 1.99689574e-04 1.04453649e-04
  1.09580092e-04]
 [9.44388305e-05 6.50720700e-05 1.04453649e-04 1.44479125e-04
  9.39382717e-05]
 [9.97317367e-05 7.23755686e-05 1.09580092e-04 9.39382717e-05
  1.56739148e-04]]


In [5]:
# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
# Check the shape of the eigenvalues and eigenvectors
print(eigenvalues.shape)
print(eigenvectors.shape)
# Check the first few rows of the eigenvalues and eigenvectors
print(eigenvalues[:48])
print(eigenvectors[:5, :48])

(48,)
(48, 48)
[4.85646910e-03 7.72405614e-04 3.73843986e-04 3.00320831e-04
 2.38502060e-04 2.14943458e-04 1.73375179e-04 1.64694082e-04
 1.40161930e-04 1.22443600e-04 1.13805739e-04 1.03877275e-04
 9.21132080e-05 8.56686298e-05 8.22240993e-05 7.72653014e-05
 7.29343543e-05 6.29742004e-05 5.94361639e-05 5.25365259e-05
 4.96636636e-05 4.73859492e-05 4.44306595e-05 4.31827862e-05
 3.76125266e-05 3.45307013e-05 3.13835407e-05 2.92198340e-05
 2.81809421e-05 2.69674219e-05 2.68909133e-06 2.38241316e-05
 2.29321263e-05 2.24962718e-05 4.18890166e-06 5.31214879e-06
 6.15895386e-06 6.78244803e-06 7.37075586e-06 8.73463369e-06
 1.81712810e-05 1.73300895e-05 1.61813629e-05 1.01748283e-05
 1.42110165e-05 1.15380420e-05 1.24867219e-05 1.33708194e-05]
[[ 1.42094202e-01 -1.02750223e-01 -1.15368121e-01  3.88262809e-01
   6.97497079e-01 -4.52809600e-01  3.99985839e-02  4.06242273e-02
   5.82833142e-02  7.65437351e-02 -5.68324799e-02  3.68233647e-02
   9.87676124e-02 -4.99645565e-02 -3.73702305e-02  2.5

In [6]:
sorted_indices = np.argsort(eigenvalues)[::-1]
print(sorted_indices)
# Sort the eigenvalues and eigenvectors
sorted_eigenvalues = eigenvalues[sorted_indices]
sorted_eigenvectors = eigenvectors[:, sorted_indices]
print(sorted_eigenvalues.shape)
print(sorted_eigenvectors.shape)

print(eigenvectors[:5, :48])
print(sorted_eigenvectors[:5, :48])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 31 32 33 40 41 42 44 47 46 45 43 39 38 37 36 35 34 30]
(48,)
(48, 48)
[[ 1.42094202e-01 -1.02750223e-01 -1.15368121e-01  3.88262809e-01
   6.97497079e-01 -4.52809600e-01  3.99985839e-02  4.06242273e-02
   5.82833142e-02  7.65437351e-02 -5.68324799e-02  3.68233647e-02
   9.87676124e-02 -4.99645565e-02 -3.73702305e-02  2.56690189e-02
  -2.75557858e-02 -1.81168568e-01 -1.21236987e-02 -3.31801535e-03
   7.26157890e-04 -1.00272670e-01  6.65908627e-02 -2.08440733e-02
  -2.52675145e-03  6.00564572e-03  8.48274664e-02 -5.74064050e-03
  -2.00373539e-02  1.55766481e-02 -4.76057251e-02  4.76936987e-02
  -3.96520793e-02  1.66167045e-02 -5.97703900e-02  4.74251675e-02
  -5.02746682e-02 -4.74892170e-02 -4.88728267e-03 -1.33598703e-02
   1.11847670e-02 -3.28797223e-02  3.36900935e-02 -7.35223219e-03
   6.07881399e-02  6.30556794e-03  4.84635326e-02 -1.58894006e-03]
 [ 1.00854705e-01  2.54325496e-02 -3.80185369